name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test main.py
        run: |
          output=$(python main.py)
          test "$output" = "Hello from main.py"
